version       = "0.1.0"
author        = "Talos"
description   = "Talos core shared library"
license       = "MIT"
srcDir        = "src"
requires "nim >= 2.0.0"
requires "db_connector >= 0.1.0"
requires "dimscord >= 1.0.0"
switch("path", "src")

task test, "Run all tests":
  exec "nim c -d:ssl -r tests/tconfig.nim"
  exec "nim c -d:ssl -r tests/ttoken_counter.nim"
  exec "nim c -d:ssl --threads:on -r tests/tmemory.nim"
  exec "nim c -d:ssl --threads:on -r tests/tllm_client.nim"
  exec "nim c -d:ssl -r tests/ttool_registry.nim"
  exec "nim c -d:ssl -r tests/test_message_chunker.nim"
  exec "nim c -d:ssl -r tests/test_discord_mocks.nim"
  exec "nim c -d:ssl -r tests/test_discord_commands.nim"
  exec "nim c -d:ssl -r tests/test_discord_bot.nim"
  exec "nim c -d:ssl --threads:on -r tests/test_e2e_discord.nim"
  exec "nim c -d:ssl -r tests/test_discord_config.nim"
  exec "nim c -d:ssl -r tests/test_permission.nim"
  exec "nim c -d:ssl -r tests/test_file_path_validator.nim"
  exec "nim c -d:ssl -r tests/test_file_tool.nim"
  exec "nim c -d:ssl -r tests/test_mock_server.nim"
  exec "nim c -d:ssl -r tests/test_rate_limit.nim"
  exec "nim c -d:ssl -r tests/test_thread_mapping.nim"
  exec "nim c -d:ssl -r tests/test_thread_reconnection.nim"
  exec "nim c -d:ssl --threads:on -r tests/test_mcp_client.nim"
  exec "nim c -d:ssl -r tests/test_mcp_tool.nim"
  exec "nim c -d:ssl -r tests/test_persona.nim"
  exec "nim c -d:ssl --threads:on -r tests/test_daemon_delegation.nim"
